---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drift-server-spack-io
  namespace: spack
  labels:
    app: drift-server-spack-io
    svc: web
spec:
  selector:
    matchLabels:
      app: drift-server-spack-io
      svc: web
  replicas: 2
  template:
    metadata:
      labels:
        app: drift-server-spack-io
        svc: web
    spec:
      containers:
      - name: web
        image: "ghcr.io/autamus/drif-server:latest"
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: DRIFTSERVER_PORT
          value: "8080"
        - name: DRIFTSERVER_DATABASE_TYPE
          value: "mysql"
        - name: DRIFTSERVER_DATABASE_DSN
          valueFrom:
            secretKeyRef:
              name: drift-server-secrets
              key: driftserver_database_dsn
        - name: DRIFTSERVER_USER
          valueFrom:
            secretKeyRef:
              name: drift-server-secrets
              key: driftserver_user
        - name: DRIFTSERVER_PASS
          valueFrom:
            secretKeyRef:
              name: drift-server-secrets
              key: driftserver_pass
      nodeSelector:
        spack.io/node-pool: base
